-- ==============================================================================
-- UPDATE SOAL KUIS KESEHATAN REPRODUKSI & PUBERTAS (AGAR LEBIH UMUM & EDUKATIF)
-- Platform: SIGMA Platform (SMPN 4 Sumberjambe)
-- Jalankan skrip ini di Supabase SQL Editor untuk memperbarui soal kategori 'pubertas'
-- ==============================================================================

-- 1. Hapus soal pubertas lama
DELETE FROM public.quizzes WHERE category = 'pubertas';

-- 2. Masukkan 10 soal pubertas baru yang lebih umum, inklusif, dan edukatif
INSERT INTO public.quizzes (category, question_text, options, correct_answer, explanation) VALUES
  ('pubertas', 'Apa yang dimaksud dengan masa pubertas pada seorang remaja?', ARRAY['Masa ketika seseorang mulai berhenti belajar di sekolah', 'Masa peralihan alami dari anak-anak menuju dewasa yang ditandai perubahan fisik, psikologis, dan kematangan organ reproduksi', 'Kondisi saat tubuh mengalami penurunan daya tahan fisik secara drastis', 'Masa di mana seseorang tidak lagi membutuhkan bimbingan keluarga'], 1, 'Pubertas adalah fase transisi alami yang dialami setiap manusia dari masa anak-anak menuju dewasa. Pada masa ini, terjadi pematangan fisik, perubahan emosional, serta perkembangan sistem reproduksi secara bertahap.'),
  ('pubertas', 'Menurut Organisasi Kesehatan Dunia (WHO), apa yang dimaksud dengan kesehatan reproduksi?', ARRAY['Keadaan di mana seseorang tidak pernah mengalami demam atau flu', 'Kemampuan fisik untuk berolahraga berat tanpa memerlukan istirahat', 'Keharusan untuk selalu berada di dalam ruangan agar terhindar dari debu', 'Keadaan sehat seutuhnya secara fisik, mental, dan sosial dalam segala hal yang berkaitan dengan sistem serta fungsi reproduksi'], 3, 'Kesehatan reproduksi tidak hanya diartikan sebagai bebas dari penyakit atau kecacatan, melainkan mencakup kesejahteraan fisik, mental, dan sosial yang utuh dalam merawat serta memahami fungsi tubuh.'),
  ('pubertas', 'Perubahan fisik umum yang dialami oleh remaja laki-laki maupun perempuan saat memasuki masa pubertas adalah...', ARRAY['Pertumbuhan tinggi dan berat badan yang pesat (growth spurt) serta perkembangan proporsi tubuh', 'Penurunan kebutuhan jam tidur secara otomatis menjadi hanya 2 jam per hari', 'Perubahan warna pigmen kulit secara menyeluruh setiap pekan', 'Berhentinya proses metabolisme dan pembentukan energi di dalam tubuh'], 0, 'Selama pubertas, hormon pertumbuhan bekerja aktif sehingga remaja mengalami lonjakan pertumbuhan (growth spurt), seperti bertambahnya tinggi badan, menguatnya otot dan tulang, serta perubahan bentuk tubuh.'),
  ('pubertas', 'Mengapa menjaga kebersihan diri (personal hygiene) menjadi sangat penting saat memasuki masa pubertas?', ARRAY['Supaya tidak perlu mengonsumsi makanan bergizi setiap hari', 'Karena aktivitas kelenjar keringat dan minyak meningkat, sehingga tubuh butuh perawatan ekstra agar tetap bersih dan sehat', 'Karena remaja dilarang membasuh tubuh dengan air mengalir', 'Agar pakaian yang dikenakan tidak perlu dicuci dalam waktu lama'], 1, 'Saat pubertas, aktivitas kelenjar keringat dan kelenjar minyak meningkat. Mandi teratur minimal dua kali sehari dan memakai pakaian bersih membantu mencegah timbulnya bau badan, jerawat, serta iritasi kulit.'),
  ('pubertas', 'Selain perubahan fisik, perubahan emosional apa yang wajar dirasakan oleh remaja selama masa pubertas?', ARRAY['Hilangnya memori masa kecil secara permanen', 'Rasa cemas yang membuat seseorang tidak bisa diajak berkomunikasi sama sekali', 'Suasana hati yang lebih dinamis (mood swing) serta proses pencarian identitas diri dan kemandirian', 'Ketiadaan perasaan empati terhadap sesama teman'], 2, 'Fluktuasi hormon dan perkembangan kognitif di masa pubertas wajar membuat suasana hati remaja lebih dinamis. Hal ini adalah proses normal menuju kedewasaan dan pembentukan karakter diri yang matang.'),
  ('pubertas', 'Apa peran asupan gizi seimbang dalam mendukung masa pertumbuhan remaja saat pubertas?', ARRAY['Menggantikan seluruh kebutuhan tidur malam dan waktu istirahat tubuh', 'Membatasi pertumbuhan tinggi badan agar tidak bertambah terlalu cepat', 'Menyediakan energi dan nutrisi yang dibutuhkan tulang, otot, serta organ tubuh yang sedang berkembang', 'Menghilangkan kebutuhan cairan sehingga tidak perlu banyak minum air putih'], 2, 'Gizi seimbang yang kaya akan protein, kalsium, zat besi, vitamin, dan serat sangat dibutuhkan untuk memaksimalkan pertumbuhan tulang, perkembangan otot, dan menjaga daya tahan tubuh remaja tetap prima.'),
  ('pubertas', 'Bagaimana sikap yang bijak dalam menyikapi perbedaan waktu dan kecepatan pubertas antarteman sebaya?', ARRAY['Membanding-bandingkan dan mengejek teman yang pertumbuhan fisiknya berbeda', 'Menghargai dan menerima perbedaan karena setiap orang memiliki proses tumbuh kembang alami yang unik', 'Memaksa teman mengonsumsi suplemen tanpa anjuran dokter', 'Menghindari bergaul dengan teman yang tubuhnya bertambah tinggi lebih cepat'], 1, 'Setiap individu memiliki jadwal biologis dan genetik yang berbeda. Menghargai proses tumbuh kembang diri sendiri dan orang lain menciptakan lingkungan pergaulan yang sehat, positif, dan bebas perundungan (bullying).'),
  ('pubertas', 'Manfaat utama dari rutin berolahraga dan aktif bergerak bagi remaja di masa pubertas adalah...', ARRAY['Memperkuat struktur tulang dan otot, menjaga kebugaran tubuh, serta membantu mengelola stres', 'Menghilangkan kebutuhan mandi dan membersihkan badan setelah beraktivitas', 'Membuat tubuh tidak memerlukan asupan makanan sehat lagi', 'Menyebabkan tubuh berhenti memproduksi hormon pertumbuhan'], 0, 'Olahraga teratur merangsang hormon pertumbuhan, meningkatkan kepadatan tulang dan kekuatan otot, serta memicu pelepasan hormon endorfin yang membantu pikiran lebih rileks dan bersemangat.'),
  ('pubertas', 'Penerapan Pola Hidup Bersih dan Sehat (PHBS) yang dianjurkan bagi remaja dalam keseharian adalah...', ARRAY['Mengurangi minum air putih agar terhindar dari berkeringat', 'Hanya mencuci tangan jika terlihat noda tebal di telapak tangan', 'Menggunakan wewangian secara berlebihan sebagai pengganti mandi pagi', 'Mandi teratur minimal dua kali sehari, memakai pakaian bersih, dan rajin mencuci tangan'], 3, 'Pola Hidup Bersih dan Sehat (PHBS) seperti mandi dua kali sehari, menjaga pakaian tetap bersih dan kering, serta mencuci tangan dengan sabun secara berkala merupakan kunci menjaga kesehatan kulit dan daya tahan tubuh.'),
  ('pubertas', 'Jika kamu merasa bingung atau memiliki kekhawatiran tentang perubahan tubuhmu saat puber, tindakan apa yang paling tepat?', ARRAY['Berkonsultasi dan bercerita secara terbuka kepada orang tua, guru BK, atau konselor/tenaga medis tepercaya', 'Memendam rasa khawatir sendirian karena merasa canggung atau takut', 'Mencari jawaban di forum internet tanpa memeriksa kebenaran informasinya', 'Mengikuti kabar burung dan mitos yang beredar di media sosial'], 0, 'Orang tua, guru bimbingan konseling (BK), dan tenaga kesehatan merupakan sumber informasi yang aman, ilmiah, dan tepercaya untuk diajak berdiskusi tentang masa pubertas dan kesehatan diri.');
