-- ==============================================================================
-- MIGRASI DATABASE: SEEDING 50 SOAL KUIS EDUKASI SMP KE TABEL QUIZZES
-- Platform: SIGMA Platform (SMPN 4 Sumberjambe)
-- Jalankan skrip ini di Supabase SQL Editor (Dashboard Supabase -> SQL Editor -> New Query)
-- ==============================================================================

-- 1. Pastikan ekstensi pgcrypto aktif untuk gen_random_uuid()
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- 2. Pastikan tabel quizzes ada (sesuai struktur tabel Supabase Anda)
CREATE TABLE IF NOT EXISTS public.quizzes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  category text NOT NULL,
  question_text text NOT NULL,
  options text[] NOT NULL,
  correct_answer integer NOT NULL,
  explanation text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT quizzes_pkey PRIMARY KEY (id)
);

-- 3. Row Level Security (RLS) agar siswa bisa baca & admin bisa kelola
ALTER TABLE public.quizzes ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public read quizzes" ON public.quizzes;
CREATE POLICY "Public read quizzes"
  ON public.quizzes
  FOR SELECT
  USING (true);

DROP POLICY IF EXISTS "Allow manage quizzes" ON public.quizzes;
CREATE POLICY "Allow manage quizzes"
  ON public.quizzes
  FOR ALL
  USING (true)
  WITH CHECK (true);

-- 4. Bersihkan data kuis lama agar bersih dan tidak duplikat
TRUNCATE TABLE public.quizzes;

-- 5. Insert 50 Soal Kuis SMP Resmi (10 Soal per Kategori)
INSERT INTO public.quizzes (category, question_text, options, correct_answer, explanation) VALUES
  ('pubertas', 'Hormon utama yang memicu perkembangan fisik dan kematangan reproduksi pada remaja perempuan saat pubertas adalah...', ARRAY['Testosteron', 'Estrogen dan Progesteron', 'Adrenalin', 'Melatonin'], 1, 'Hormon estrogen dan progesteron diproduksi oleh ovarium (indung telur) saat pubertas dan memicu perkembangan payudara, pinggul, serta siklus menstruasi.'),
  ('pubertas', 'Apa istilah medis untuk menstruasi pertama yang dialami oleh remaja perempuan?', ARRAY['Menarche', 'Menopause', 'Ovulasi', 'Pubarke'], 0, 'Menarche adalah peristiwa menstruasi pertama pada perempuan, menandakan organ reproduksi mulai aktif memproduksi sel telur secara alami.'),
  ('pubertas', 'Berapa kali minimal kita sebaiknya mengganti pakaian dalam setiap hari agar area intim tetap sehat?', ARRAY['1 kali sehari', 'Minimal 2 kali sehari', 'Tiga hari sekali', 'Hanya saat pakaian kotor saja'], 1, 'Mengganti pakaian dalam minimal 2 kali sehari (terutama setelah beraktivitas atau berkeringat) mencegah kelembapan berlebih yang memicu jamur dan bakteri.'),
  ('pubertas', 'Saat remaja perempuan sedang mengalami menstruasi, berapa jam sekali pembalut sebaiknya diganti secara teratur?', ARRAY['1 kali sehari saat malam hari', 'Setiap 3 sampai 4 jam sekali atau saat sudah terasa penuh', 'Dua hari sekali', 'Hanya saat mandi pagi saja'], 1, 'Mengganti pembalut tiap 3-4 jam menjaga kebersihan area kewanitaan, mencegah penumpukan kuman, dan menjaga rasa nyaman selama beraktivitas di sekolah.'),
  ('pubertas', 'Peristiwa alami keluarnya cairan sperma saat tidur pada remaja laki-laki yang sedang pubertas biasa disebut...', ARRAY['Mengigau', 'Mimpi basah', 'Sleepwalking', 'Insomnia'], 1, 'Mimpi basah adalah hal yang wajar, normal, dan sehat bagi remaja laki-laki, menandakan testis sudah mulai aktif memproduksi cairan sperma.'),
  ('pubertas', 'Perubahan fisik yang umumnya terjadi pada remaja laki-laki saat memasuki masa pubertas adalah...', ARRAY['Suara menjadi lebih berat dan jakun mulai terlihat', 'Mengalami siklus menstruasi', 'Pinggul melebar secara drastis', 'Tinggi badan berhenti bertambah'], 0, 'Saat pubertas, hormon testosteron pada laki-laki memicu penebalan pita suara (suara memberat), tumbuhnya jakun di leher, serta pelebaran bahu dada.'),
  ('pubertas', 'Cara yang benar membersihkan area kemaluan bagi perempuan setelah buang air kecil adalah...', ARRAY['Dari arah belakang ke depan', 'Dari arah depan ke belakang menuju anus', 'Menggunakan sabun mandi berbusa tebal', 'Cukup diusap tanpa dibilas air bersih'], 1, 'Membasuh dari arah depan ke belakang mencegah kuman dan bakteri dari anus berpindah ke saluran kencing yang dapat menyebabkan infeksi kandung kemih.'),
  ('pubertas', 'Saat pubertas, kelenjar keringat dan minyak bekerja lebih aktif. Cara terbaik agar tidak bau badan dan tidak mudah berjerawat adalah...', ARRAY['Memakai parfum sebanyak-banyaknya tanpa mandi', 'Mandi teratur 2 kali sehari dan mencuci wajah dengan sabun yang lembut', 'Memencet jerawat yang baru tumbuh', 'Menghindari minum air putih'], 1, 'Mandi teratur dan mencuci muka dengan lembut membersihkan debu serta minyak berlebih di pori-pori kulit secara sehat tanpa memicu iritasi.'),
  ('pubertas', 'Setelah buang air atau mandi, apa yang harus dilakukan sebelum memakai celana dalam kembali?', ARRAY['Membiarkannya basah dan langsung memakai celana tebal', 'Mengeringkan area kemaluan dengan handuk atau tisu bersih', 'Mengoleskan bedak tabur tebal', 'Memakai pakaian yang masih lembap'], 1, 'Mengeringkan area intim dengan handuk atau tisu bersih memastikan pakaian dalam tidak basah atau lembap, sehingga bebas dari rasa gatal dan iritasi.'),
  ('pubertas', 'Jika kamu memiliki pertanyaan atau kebingungan seputar perubahan tubuhmu saat puber, kepada siapa sebaiknya kamu bertanya?', ARRAY['Orang tua, guru BK, atau tenaga kesehatan/konselor sebaya tepercaya', 'Orang asing yang baru dikenal di media sosial', 'Membaca forum gosip acak di internet', 'Memendamnya sendirian karena merasa malu'], 0, 'Orang tua, guru BK, dan konselor kesehatan sebaya adalah sumber informasi yang tepat, aman, ilmiah, dan tepercaya untuk diajak berdiskusi tentang pubertas.'),
  ('pernikahan-anak', 'Berapakah batas usia minimal untuk melangsungkan pernikahan baik bagi laki-laki maupun perempuan sesuai UU No. 16 Tahun 2019 di Indonesia?', ARRAY['16 tahun', '17 tahun', '18 tahun', '19 tahun'], 3, 'Undang-Undang No. 16 Tahun 2019 menetapkan bahwa perkawinan hanya diizinkan apabila pria dan wanita sudah mencapai umur minimal 19 tahun demi melindungi masa depan anak.'),
  ('pernikahan-anak', 'Mengapa perempuan berusia di bawah 19 tahun sangat berisiko jika hamil dan melahirkan?', ARRAY['Panggul dan organ reproduksi belum berkembang matang sempurna', 'Nafsu makan berkurang drastis', 'Kuku jari tumbuh lebih cepat', 'Tinggi badan akan bertambah dua kali lipat'], 0, 'Tulang panggul perempuan baru matang sempurna di atas usia 19 tahun. Hamil di usia terlalu muda berisiko tinggi persalinan macet, pendarahan hebat, hingga preeklamsia.'),
  ('pernikahan-anak', 'Mengapa perkawinan usia anak dapat memperpanjang rantai kemiskinan antargenerasi?', ARRAY['Karena dilarang menabung oleh bank', 'Memicu putus sekolah sehingga membatasi keterampilan untuk memperoleh pekerjaan layak', 'Karena biaya pernikahan terlalu murah', 'Karena pasangan baru wajib pindah dari desa'], 1, 'Pernikahan dini sering memaksa remaja meninggalkan bangku sekolah. Rendahnya tingkat pendidikan membatasi akses keterampilan untuk memperoleh pekerjaan dengan pendapatan yang layak.'),
  ('pernikahan-anak', 'Bayi yang dilahirkan oleh ibu yang masih berusia anak-anak memiliki risiko kesehatan lebih tinggi mengalami...', ARRAY['Gigi tumbuh sejak hari pertama lahir', 'Stunting (gagal tumbuh) dan berat badan lahir rendah (BBLR)', 'Kelebihan sel darah putih alami', 'Penglihatan super di malam hari'], 1, 'Karena rahim dan asupan nutrisi ibu remaja belum matang optimal, janin berisiko lahir sebelum waktunya (prematur), berbobot rendah, dan rentan stunting.'),
  ('pernikahan-anak', 'Mengapa kesiapan mental dan emosional sangat penting sebelum seseorang memutuskan berumah tangga di masa dewasa?', ARRAY['Supaya bisa pamer di media sosial', 'Membina keluarga butuh kematangan emosi, tanggung jawab nafkah, dan saling menghargai', 'Agar tidak perlu belajar dan sekolah lagi', 'Supaya bebas bermain game sepanjang hari'], 1, 'Menikah bukan sekadar hidup bersama, melainkan membutuhkan kedewasaan dalam memecahkan masalah, mengasuh anak, serta stabilitas emosi yang matang.'),
  ('pernikahan-anak', 'Apa faktor yang sering menjadi pemicu terjadinya perkawinan usia anak di lingkungan masyarakat?', ARRAY['Terlalu rajin membaca buku pelajaran', 'Tekanan ekonomi keluarga, pergaulan bebas tanpa batas, dan kurangnya pemahaman kesehatan', 'Gemar berolahraga bersama teman sekolah', 'Aktif mengikuti ekstrakurikuler kepramukaan'], 1, 'Himpitan ekonomi, informasi kesehatan reproduksi yang minim, serta pengaruh pergaulan bebas sering kali menjadi pemicu utama pernikahan dini.'),
  ('pernikahan-anak', 'Apa yang sebaiknya kamu lakukan jika ada teman sekelas yang bercerita bahwa ia terancam dinikahkan paksa oleh keluarganya?', ARRAY['Menertawakan dan menyebarkan gosip ke teman lain', 'Mendengarkan dengan peduli dan menyarankan untuk lapor ke guru BK atau dinas perlindungan anak', 'Menyuruh teman tersebut kabur sendirian tanpa tujuan', 'Pura-pura tidak mendengar dan menjauhinya'], 1, 'Guru BK dan lembaga perlindungan anak memiliki wewenang untuk memberikan mediasi keluarga dan bantuan advokasi agar hak bersekolah anak tetap terlindungi.'),
  ('pernikahan-anak', 'Menikah di usia yang cukup dan matang (di atas 19 tahun) memberikan banyak manfaat, KECUALI...', ARRAY['Organ reproduksi sudah siap untuk menjalani kehamilan yang sehat', 'Pendidikan dasar dan menengah sudah selesai ditempuh', 'Menghilangkan seluruh kewajiban untuk bekerja keras dan bertanggung jawab', 'Kematangan berpikir dan kestabilan emosi jauh lebih baik'], 2, 'Menikah di usia dewasa tetap menuntut tanggung jawab dan kerja keras, namun dijalani dengan kesiapan fisik, mental, dan ekonomi yang jauh lebih matang.'),
  ('pernikahan-anak', 'Program pemerintah mengenai ''Pendewasaan Usia Perkawinan (PUP)'' bertujuan untuk...', ARRAY['Melarang semua orang untuk menikah seumur hidup', 'Mendorong remaja merencanakan masa depan dan matang sebelum membina rumah tangga', 'Memaksa anak SMP untuk bekerja mencari nafkah', 'Mengurangi jumlah sekolah di setiap kecamatan'], 1, 'Program PUP mengedukasi masyarakat agar merencanakan pernikahan pada usia ideal demi melahirkan generasi yang sehat, cerdas, dan sejahtera lahir batin.'),
  ('pernikahan-anak', 'Peran terbaik yang bisa dilakukan oleh siswa SMP seperti kamu dalam mencegah pernikahan anak adalah...', ARRAY['Fokus belajar, aktif mengejar cita-cita, dan saling mengingatkan teman tentang bahaya nikah dini', 'Mencoba pacaran bebas tanpa batas', 'Memutuskan berhenti sekolah demi mencari uang jajan', 'Menolak berteman dengan orang yang pintar'], 0, 'Remaja yang berpendidikan dan saling mendukung dapat menjadi agen perubahan positif di lingkungannya untuk menolak perkawinan anak.'),
  ('hak-anak', 'Menurut undang-undang perlindungan anak dan konvensi resmi PBB, batasan seseorang disebut sebagai ''anak'' adalah...', ARRAY['Setiap orang yang berusia di bawah 18 tahun', 'Hanya mereka yang masih balita', 'Hanya mereka yang belum masuk sekolah', 'Siapa saja yang belum memiliki pekerjaan tetap'], 0, 'Berdasarkan UU Perlindungan Anak dan Konvensi PBB, anak adalah siapa saja yang belum berusia 18 tahun, termasuk anak yang masih dalam kandungan.'),
  ('hak-anak', 'Berikut ini adalah empat pilar hak dasar anak berdasarkan Konvensi Hak Anak PBB, KECUALI...', ARRAY['Hak kelangsungan hidup', 'Hak tumbuh kembang', 'Hak memiliki kekayaan pribadi melimpah', 'Hak perlindungan dan partisipasi'], 2, 'Empat pilar hak dasar anak adalah: hak kelangsungan hidup, hak tumbuh kembang, hak perlindungan, dan hak partisipasi. Memiliki kekayaan pribadi bukan hak dasar anak.'),
  ('hak-anak', 'Contoh pemenuhan hak tumbuh kembang anak dalam kehidupan sehari-hari adalah...', ARRAY['Memperoleh pendidikan yang layak, gizi seimbang, dan ruang bermain yang aman', 'Dibiarkan bekerja kasar di jalanan dari pagi hingga malam', 'Dilarang membaca buku pelajaran sekolah', 'Dipaksa mencari nafkah untuk orang dewasa'], 0, 'Hak tumbuh kembang menjamin anak mendapatkan pendidikan bermutu, gizi sehat, kasih sayang keluarga, serta kesempatan bermain untuk masa depan terbaiknya.'),
  ('hak-anak', 'Hak anak untuk menyuarakan pendapat dan didengarkan pandangannya dalam forum atau keluarga termasuk ke dalam pilar...', ARRAY['Hak kelangsungan hidup', 'Hak partisipasi', 'Hak monopoli', 'Hak kepemilikan barang'], 1, 'Hak partisipasi menjamin kebebasan anak untuk menyampaikan aspirasi, didengarkan pandangannya, serta diikutsertakan dalam dialog hal yang berkaitan dengannya.'),
  ('hak-anak', 'Jika ada anak yang dipaksa bekerja kasar seharian sehingga putus sekolah, hak apa yang paling dilanggar?', ARRAY['Hak mendapatkan waktu santai di pusat perbelanjaan', 'Hak perlindungan dari eksploitasi ekonomi dan hak atas pendidikan', 'Hak mengendarai mobil pribadi', 'Hak membeli barang elektronik mahal'], 1, 'Memaksa anak bekerja keras dan merampas hak belajarnya adalah bentuk eksploitasi anak yang melanggar hak perlindungan dan hak pendidikan dasar.'),
  ('hak-anak', 'Dokumen resmi negara yang menjadi bukti identitas sah seorang anak sejak lahir di Indonesia adalah...', ARRAY['Akta Kelahiran dan Kartu Identitas Anak (KIA)', 'Surat Izin Mengemudi (SIM)', 'Buku tabungan rekening saham', 'Kartu langganan bioskop'], 0, 'Akta kelahiran dan KIA adalah dokumen identitas resmi yang menjamin status kewarganegaraan, akses pendaftaran sekolah, dan jaminan layanan kesehatan anak.'),
  ('hak-anak', 'Apa yang dimaksud dengan prinsip ''Non-Diskriminasi'' dalam pemenuhan hak anak?', ARRAY['Semua anak berhak dilindungi tanpa membedakan suku, agama, jenis kelamin, atau kondisi fisik', 'Hanya anak yang kaya yang berhak mendapatkan pendidikan', 'Anak perempuan dilarang ikut berpendapat di kelas', 'Hanya anak yang berprestasi yang dilindungi hukum'], 0, 'Prinsip non-diskriminasi menegaskan bahwa setiap anak berhak atas perlindungan dan kesempatan yang setara tanpa dibeda-bedakan latar belakangnya.'),
  ('hak-anak', 'Hak perlindungan anak memastikan bahwa setiap anak wajib dilindungi dari hal-hal berikut, KECUALI...', ARRAY['Kekerasan fisik dan pelecehan', 'Perundungan (bullying) di sekolah', 'Bimbingan belajar dan nasihat penuh kasih dari orang tua', 'Penelantaran dan eksploitasi'], 2, 'Nasihat dan bimbingan belajar positif dari orang tua adalah wujud kasih sayang dan pengasuhan keluarga yang baik, bukan bentuk kekerasan.'),
  ('hak-anak', 'Siapakah pihak yang paling bertanggung jawab dalam memenuhi dan melindungi hak-hak anak?', ARRAY['Keluarga, orang tua, sekolah, masyarakat sekitar, dan pemerintah', 'Hanya anak itu sendiri', 'Teman bermain game saja', 'Akun media sosial di internet'], 0, 'Perlindungan anak adalah tanggung jawab bersama yang melibatkan orang tua, keluarga besar, guru di sekolah, lingkungan masyarakat, dan negara.'),
  ('hak-anak', 'Wadah organisasi resmi di Indonesia yang dibentuk agar anak dan remaja dapat menyuarakan aspirasi kepada pemerintah disebut...', ARRAY['Forum Anak', 'Klub Balap Liar', 'Komite Karyawan', 'Arisan Remaja'], 0, 'Forum Anak adalah wadah partisipasi resmi binaan KemenPPPA agar anak dan remaja dapat menyalurkan pandangan serta aspirasinya bagi pembangunan daerah.'),
  ('kekerasan-seksual', 'Area tubuh mana sajakah yang merupakan area pribadi dan TIDAK BOLEH disentuh atau dilihat oleh orang lain sembarangan?', ARRAY['Area yang tertutup baju renang (dada, bibir, kemaluan, dan pantat)', 'Kuku jari tangan dan kaki', 'Rambut kepala saja', 'Siku dan telapak tangan'], 0, 'Bagian pribadi tubuh kita meliputi area yang tertutup pakaian renang (dada, kemaluan, pantat, dan bibir). Tidak ada yang boleh menyentuh, melihat, atau memotretnya sembarangan!'),
  ('kekerasan-seksual', 'Apa contoh dari ''Sentuhan Aman'' (Safe Touch) dalam pergaulan sehari-hari?', ARRAY['Sentuhan rahasia yang tidak boleh diceritakan ke orang tua', 'Berjabat tangan dengan teman atau mencium tangan guru/orang tua saat berpamitan', 'Sentuhan paksa yang membuatmu merasa takut dan malu', 'Sentuhan di area dada oleh orang yang baru dikenal'], 1, 'Sentuhan aman adalah sentuhan hangat penuh rasa hormat, membuatmu merasa nyaman, wajar, dan tidak disembunyikan sebagai rahasia yang mencurigakan.'),
  ('kekerasan-seksual', 'Apa yang harus kamu lakukan jika ada orang (bahkan yang kamu kenal) berusaha menyentuh area pribadimu atau mengajak melakukan hal tak senonoh?', ARRAY['Diam saja karena takut dia marah', 'Katakan TIDAK dengan tegas, lari ke tempat aman, dan segera lapor ke orang tua atau guru', 'Menuruti permintaannya agar diberi uang saku', 'Menyimpan rahasia tersebut sendirian di buku harian'], 1, 'Ingat aturan emas: TOLAK, LARI, LAPORKAN! Tegaskan penolakanmu, jauhi orang tersebut, dan langsung ceritakan kepada orang dewasa yang kamu percaya.'),
  ('kekerasan-seksual', 'Seseorang di media sosial meminta kamu mengirimkan foto tanpa busana atau pakaian dalam dengan janji akan diberi hadiah. Apa tindakanmu?', ARRAY['Mengirimkannya karena dia berjanji tidak akan menyebarkannya', 'Tolak tegas, jangan kirimkan foto apa pun, blokir akunnya, dan beri tahu orang tua/guru', 'Mengirimkan foto teman lain', 'Membalas dengan mengirimkan nomor rekening bank'], 1, 'Ini adalah modus Kekerasan Berbasis Gender Online (KBGO). Jangan pernah membagikan foto pribadi kepada siapa pun di internet karena berisiko disalahgunakan untuk pemerasan.'),
  ('kekerasan-seksual', 'Mengapa pelaku kekerasan atau pelecehan seksual sering menyuruh korbannya untuk ''merahasiakan kejadian ini''?', ARRAY['Karena pelaku ingin memberi pesta kejutan', 'Untuk menakut-nakuti korban agar kejahatan pelaku tidak terbongkar', 'Karena itu adalah permainan rahasia yang menyenangkan', 'Agar korban disayang oleh keluarga di rumah'], 1, 'Pelaku mengancam agar korban merasa takut dan bersalah. Ingat: korban sama sekali tidak bersalah, kesalahan 100% ada pada pihak pelaku!'),
  ('kekerasan-seksual', 'Apakah menggoda dengan siulan nakal (catcalling), komentar berbau porno, atau memegang tubuh tanpa izin termasuk bentuk pelecehan seksual?', ARRAY['Ya, itu adalah pelecehan verbal dan fisik yang melanggar kenyamanan orang lain', 'Tidak, itu hanya lelucon biasa yang tidak perlu dipikirkan', 'Hanya pelecehan jika dilakukan di malam hari', 'Hal yang wajar dilakukan antar sesama remaja'], 0, 'Segala bentuk ucapan, siulan bernada cabul, maupun sentuhan tubuh tanpa persetujuan adalah bentuk pelecehan yang merendahkan martabat orang lain.'),
  ('kekerasan-seksual', 'Apa yang dimaksud dengan konsep ''Konsen'' (Consent) atau persetujuan dalam interaksi antarteman?', ARRAY['Memaksa teman menuruti apa pun keinginan kita', 'Kesepakatan sukarela yang diberikan dengan sadar tanpa paksaan atau ancaman', 'Mengambil barang teman tanpa izin terlebih dahulu', 'Berpura-pura setuju karena takut dijauhi teman sekelompok'], 1, 'Konsen berarti kedua belah pihak benar-benar setuju dan merasa nyaman secara sukarela tanpa ada rasa takut, terpaksa, ataupun intimidasi.'),
  ('kekerasan-seksual', 'Kapan seorang dokter atau tenaga medis boleh memeriksa area pribadi tubuhmu?', ARRAY['Kapan saja tanpa izin', 'Hanya saat pemeriksaan kesehatan resmi dan wajib didampingi oleh orang tua atau perawat', 'Di ruangan tertutup sepi tanpa memberi tahu orang tua', 'Saat tidak ada keluhan sakit sama sekali'], 1, 'Pemeriksaan medis di area sensitif hanya boleh dilakukan untuk alasan kesehatan profesional dan wajib selalu didampingi oleh orang tua atau tenaga medis pendamping.'),
  ('kekerasan-seksual', 'Jika seorang sahabat menceritakan bahwa dia mengalami pelecehan seksual, sikap terbaik apa yang harus kamu tunjukkan?', ARRAY['Menyalahkan pakaiannya atau menuduhnya berbohong', 'Percayai ceritanya, beri dukungan moral, dan temani dia melapor ke guru BK/orang tua', 'Menyebarkan ceritanya di grup chat sekolah agar viral', 'Menyuruhnya melupakan kejadian itu begitu saja'], 1, 'Jangan pernah menyalahkan korban (victim blaming). Dengarkan ceritanya dengan empati, jaga privasinya, dan bantu dia mendapatkan pertolongan aman dari pihak berwenang.'),
  ('kekerasan-seksual', 'Layanan pengaduan resmi dari Kementerian Pemberdayaan Perempuan dan Perlindungan Anak (KemenPPPA) untuk pelaporan kekerasan adalah...', ARRAY['Sahabat Perempuan dan Anak (Hotline SAPA 129)', 'Call Center Pulsa Darurat', 'Hotline Game Online Nusantara', 'Layanan Cuaca Nasional'], 0, 'SAPA 129 adalah layanan hotline resmi bebas pulsa untuk melaporkan kekerasan terhadap perempuan dan anak di seluruh wilayah Indonesia.'),
  ('kesehatan-mental', 'Apa yang dimaksud dengan ''kesehatan mental'' yang baik pada diri seorang remaja?', ARRAY['Selalu tertawa bahagia setiap saat tanpa pernah merasa sedih', 'Kondisi emosi, pikiran, dan perilaku yang sehat sehingga mampu mengatasi stres dan belajar dengan baik', 'Tidak pernah memiliki masalah sama sekali di rumah maupun sekolah', 'Memiliki banyak barang mewah dan pengikut media sosial'], 1, 'Kesehatan mental yang baik membuat kita mampu berpikir jernih, mengelola emosi (baik rasa senang maupun sedih), dan beradaptasi menghadapi tantangan belajar.'),
  ('kesehatan-mental', 'Menghadapi pekan ujian sekolah yang membuatmu cemas dan tegang, cara mengelola stres yang paling sehat adalah...', ARRAY['Begadang semalaman sambil terus meminum kopi berlebihan', 'Mencicil belajar secara teratur, latihan pernapasan santai, dan tidur yang cukup', 'Menyerah dan memutuskan tidak ikut ujian sama sekali', 'Melampiaskan kemarahan dengan membentak teman dan adik'], 1, 'Mencicil belajar membuat otak tidak kelelahan, sementara tidur cukup dan latihan napas dalam membantu menenangkan detak jantung serta meredakan kecemasan.'),
  ('kesehatan-mental', 'Ciri-ciri hubungan pertemanan yang sehat (healthy friendship) adalah...', ARRAY['Saling mendukung dalam hal positif, saling menghargai, dan tidak menjatuhkan teman', 'Hanya mau berteman jika kita mentraktir makanan setiap hari', 'Suka mengajak kita melanggar aturan sekolah demi terlihat keren', 'Sering mengejek kekurangan fisik kita di depan orang banyak'], 0, 'Pertemanan yang sehat dibangun atas rasa saling percaya, kejujuran, saling menghargai batasan pribadi, dan saling menyemangati untuk berkembang bersama.'),
  ('kesehatan-mental', 'Ciri pertemanan yang tidak sehat (toxic friendship) yang perlu kamu waspadai adalah...', ARRAY['Teman yang mengajak belajar kelompok bersama di perpustakaan', 'Teman yang suka memanipulasi, sering mengejek, dan memaksa kita melakukan hal buruk', 'Teman yang meminjamkan catatan pelajaran saat kita sakit', 'Teman yang mengucapkan selamat saat kita meraih prestasi'], 1, 'Hubungan pertemanan toxic membuat kita merasa tertekan, rendah diri, dan merasa bersalah tanpa alasan. Penting untuk menetapkan batasan yang tegas.'),
  ('kesehatan-mental', 'Jika kamu merasa sangat sedih, cemas, atau hampa selama berminggu-minggu, tindakan terbaik yang harus dilakukan adalah...', ARRAY['Mengurung diri di kamar dan menolak berbicara dengan siapa pun', 'Berani bercerita kepada orang tua, guru BK, atau konselor sebaya tepercaya', 'Melakukan hal berbahaya yang merugikan tubuh sendiri', 'Berpura-pura bahagia dan memendam semua beban sendirian'], 1, 'Meminta pertolongan bukan tanda kelemahan, melainkan bukti keberanian untuk pulih. Berbagi cerita dengan orang tepercaya meringankan beban emosi kita.'),
  ('kesehatan-mental', 'Tindakan sengaja menghina, mempermalukan, atau menyebarkan gosip jahat tentang teman di media sosial disebut...', ARRAY['Cyberbullying (Perundungan Siber)', 'Diskusi Ilmiah Online', 'Kerja Kelompok Digital', 'Literasi Budaya Siber'], 0, 'Cyberbullying adalah bentuk perundungan di dunia maya yang dapat melukai kesehatan mental korban secara mendalam. Jangan pernah melakukannya!'),
  ('kesehatan-mental', 'Mengapa mengambil jeda sejenak dari media sosial (Digital Detox) bermanfaat bagi kesehatan pikiran remaja?', ARRAY['Supaya kuota internet habis terbuang sia-sia', 'Memberi pikiran waktu istirahat agar tidak terus-menerus membandingkan diri dengan kehidupan orang lain', 'Agar kita tidak memiliki teman lagi di sekolah', 'Karena layar handphone akan rusak jika sering dinyalakan'], 1, 'Terlalu lama di media sosial sering memicu rasa rendah diri dan cemas. Jeda layar membantu kita lebih fokus pada dunia nyata, hobi, dan kualitas tidur.'),
  ('kesehatan-mental', 'Apa yang sebaiknya kamu lakukan jika melihat ada teman sekelas yang sedang diejek atau dikucilkan oleh kelompok lain?', ARRAY['Ikut menertawakannya agar dianggap gaul dan punya banyak teman', 'Menemani teman tersebut, menolak ikut mengejek, dan melapor ke guru jika terus berlanjut', 'Merekam kejadian itu dan menyebarkannya di status media sosial', 'Menjauhi teman tersebut agar kita tidak ikut dijadikan sasaran'], 1, 'Menjadi pembela (upstander) dengan menunjukkan kepedulian dapat menyelamatkan rasa percaya diri dan kesehatan mental teman yang sedang dirundung.'),
  ('kesehatan-mental', 'Mengapa tidur malam yang cukup (sekitar 8-9 jam bagi remaja) sangat penting bagi kesehatan mental?', ARRAY['Supaya tidak perlu bangun pagi untuk sarapan', 'Membantu otak memulihkan energi, menstabilkan emosi, dan meningkatkan konsentrasi belajar', 'Karena mimpi malam hari otomatis meningkatkan nilai rapor', 'Supaya waktu berolahraga di siang hari berkurang'], 1, 'Kurang tidur membuat remaja mudah lelah, cemas, sensitif, dan sulit fokus di kelas. Istirahat yang cukup adalah fondasi kesehatan mental dan fisik yang prima.'),
  ('kesehatan-mental', 'Kalimat afirmasi positif terbaik yang bisa kamu katakan pada dirimu sendiri saat merasa gagal atau berbuat kesalahan adalah...', ARRAY['''Aku memang bodoh dan tidak akan pernah berhasil.''', '''Wajar jika aku berbuat salah, aku bisa belajar dari pengalaman ini dan mencoba lagi dengan lebih baik.''', '''Pasti semua orang di sekolah sekarang membenciku.''', '''Lebih baik aku tidak usah mencoba apa pun lagi seumur hidup.'''], 1, 'Menyayangi diri sendiri (self-compassion) dan berpikir positif membantu kita bangkit dari kegagalan dengan semangat baru untuk terus bertumbuh.');
